# Generated by Django 2.0.5 on 2018-05-22 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificado', models.UUIDField(default=uuid.UUID('56bdca6b-9914-458d-8947-f78aba10d0ea'), editable=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificado', models.UUIDField(default=uuid.UUID('d5a5c0d3-e884-4820-b2aa-10c3e0d3d632'), editable=False)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PR', 'Pedido Realizado'), ('SP', 'Separação em estoque'), ('EM', 'Em montagem'), ('RT', 'Realização de testes'), ('CO', 'Concluido')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificado', models.UUIDField(default=uuid.UUID('44394215-d056-481d-bbd8-65b81c25b8cf'), editable=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='produtos_pedidos', to='core.Produto'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_em_estoque', to='core.Produto'),
        ),
    ]
