# Generated by Django 2.0.5 on 2018-05-22 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('f6bb04d7-cd23-49ed-8575-9f0db8f36437'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('ffd354fc-6c51-4620-90f9-2c75f98f98a2'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('cc545918-6b1c-41b2-bdb3-ba79df328318'), editable=False),
        ),
    ]
