# Generated by Django 2.0.5 on 2018-05-22 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('b1933aed-acdc-4400-990a-d3f3411a900b'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('a25d8608-5019-4ad8-9906-777b55941599'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('594b8b45-6b06-431c-8695-86d9f8dc8c06'), editable=False),
        ),
    ]
