# Generated by Django 2.0.5 on 2018-05-22 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180522_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('3404c913-1d93-47bb-872b-df041f4f6cb3'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('303c5ce8-94c7-4b02-b369-7076d45fa1c1'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('da74f470-71bc-4ecd-88cd-9b93677dfeeb'), editable=False),
        ),
    ]
