# Generated by Django 2.0.5 on 2018-05-22 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180522_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('97521b81-e229-443e-9ae1-7c86f9008e25'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('7265a2ad-d4be-4661-be9f-76434b9a7bb6'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('1cb486f0-344f-4718-8201-5be19b9bc088'), editable=False),
        ),
    ]
