# Generated by Django 2.0.5 on 2018-05-22 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180522_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('4f0c1cdf-b08c-4d64-8d8c-e356665bee63'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('99186fe4-235e-4365-b9a4-73d91bad9a3f'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('98a179cd-4e7c-4a81-b1a4-fdfa2a42c056'), editable=False),
        ),
    ]
