# Generated by Django 2.0.5 on 2018-05-23 00:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180522_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(related_name='pedidos_produtos', to='core.Produto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('98fa3989-a43f-4ace-bab6-8bf17594cfb3'), editable=False),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('d7067da8-7335-49a9-9ba6-f1530d845891'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produtos', to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('c705f4c4-71e4-4436-9604-a376f884ca8f'), editable=False),
        ),
    ]
