# Generated by Django 2.0.5 on 2018-05-22 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180522_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('00306292-65c1-49ae-8380-ec2bf269b3f4'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('4d8bd9df-99df-4859-a509-8194114df78d'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('ad3bb4c1-c2b4-4426-8ea1-577f76d264a0'), editable=False),
        ),
    ]
