# Generated by Django 2.0.5 on 2018-05-23 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180522_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('8387dcd7-b142-4083-8874-ab31dc52f881'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('174bc678-ca34-4122-91bf-4bbe21f7117d'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('3c42c31c-4535-4929-b8be-9fb4d9bb0a32'), editable=False),
        ),
    ]
