# Generated by Django 2.0.5 on 2018-05-22 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180522_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('3c1baaee-5859-4343-a955-1173ef7eeab4'), editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('1ec9d278-eb2a-4cff-bcbb-016126be63f9'), editable=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='identificado',
            field=models.UUIDField(default=uuid.UUID('5e637a21-984a-42cd-a3eb-9cd5c041300a'), editable=False),
        ),
    ]
