# Generated by Django 2.0.5 on 2018-05-23 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180522_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='identificado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='identificado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='identificado',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('1da12d53-ea96-45dd-bbab-9aa4afa6ccea'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
