# Generated by Django 2.0.5 on 2018-05-25 02:36

from django.db import migrations, models
import loja.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(related_name='produtos_em_pedidos', to='api.Produto', validators=[loja.api.validators.validar_produto]),
        ),
    ]
