# Generated by Django 2.0.5 on 2018-05-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180524_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(related_name='produtos_em_pedidos', to='api.Produto'),
        ),
    ]
