# Generated by Django 2.0.5 on 2018-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180524_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
