# Generated by Django 2.0.5 on 2018-05-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedido_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='num',
        ),
    ]
